[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
monthly_subscription_solana = { path = "../programs/monthly_subscription_solana" }

[[bin]]
name = "app"
path = "main.rs"